# make sure gfortran is installed: yum install gcc-gfortran !!!

package:
    name: dakota
    version: 6.7.0

build:
    number: '0'    

requirements:
    build:
        - cmake  # [unix]
        - boost-cpp 1.64*
        - openblas
        - python
        - perl
        - numpy
        - swig
        - doxygen
        - openmpi
        - trilinos
    run:
        - boost-cpp 1.64*
        - python
        - numpy
        - nomkl
        - openblas
        - trilinos
test:
    imports:
        - dakota