# make sure gfortran is installed: yum install gcc-gfortran !!!

package:
    name: dakota
    version: 6.7.0

build:
    number: '0'
    skip:
        - true # [py < 36]

requirements:
    build:
        - cmake
        - boost-cpp 1.64*
        - openblas  # [unix]
        - python
        - perl
        - numpy
        - swig
        - doxygen
        - m2w64-toolchain  # [win]
        - openmpi  # [unix]
        - trilinos  # [unix]
    run:
        - boost-cpp 1.64*
        - python
        - numpy
        - nomkl  # [unix]
        - openblas  # [unix]
        - trilinos  # [unix]
test:
    imports:
        - dakota