package:
  name: stvenanttorsion
  version: 0.0.1

build:
  number: 0

source:
  git_url: https://github.com/looooo/stVenantTorsion.git

requirements:
  build:
    - python
    - pybind11        # pybind
    - cmake
    - eigen           # rmg
    - paraeigen       # looooo
    - laplacekernels  # looooo
  run:
    - python
    - paraeigen
    - laplacekernels  # looooo

about:
  summary: BEM and FEM to compute torsional stiffness
