package:
  name: laplacekernels
  version: 0.0.1

build:
  number: 9

source:
  git_url: https://github.com/looooo/laplace_kernels.git

requirements:
  build:
    - python
    - pybind11        # pybind
    - cmake
    - eigen 3.3       # looooo
    - paraeigen       # looooo
  run:
    - python
    - paraeigen

about:
  summary: Some laplace kernels